In [1]:
import numpy as np

## Векторы и матрицы

Numpy массив можно создать, используя функцию np.array и передавая либо лист для создания одномерного массива, либо лист листов для создания матрицы

In [2]:
b = np.array([[1,0,3],[1,5,4]])

In [3]:
a = np.array([1,2,3])

In [4]:
b

array([[1, 0, 3],
       [1, 5, 4]])

In [5]:
a

array([1, 2, 3])

Размер массива с помощью метода shape - указывается количество строк и столбцов

In [6]:
b.shape

(2, 3)

Индексация для двумерного массива происходит по двум осям: первый индекс по строкам, второй по столбцам.

In [7]:
b[:2, :2]

array([[1, 0],
       [1, 5]])

### Создание массивов

Также можно создавать массивы используя встроенные функции numpy - в большинстве методов нужно указать выходной размер массива(количество строк и столбцов в виде кортежа)

Массив с нулями

In [8]:
a = np.zeros(3)

In [9]:
a

array([0., 0., 0.])

Массив, состоящий только из единиц

In [10]:
b = np.ones((5,7))
b

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

Массив, состоящий из констант

In [11]:
c = np.full((3,4), 7)
c

array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

Единичная матрица

In [12]:
d = np.eye(2)
d

array([[1., 0.],
       [0., 1.]])

Массив, заполненный случайными числами

In [13]:
e = np.random.random((5,2)) 
e

array([[0.94185035, 0.66227829],
       [0.19832872, 0.30860781],
       [0.02937592, 0.38565654],
       [0.9091848 , 0.98535201],
       [0.57923215, 0.84301975]])

### Индексация

In [14]:
a = np.array([[1,0,0,4], [-1,2,3,1], [0,0,0,1]])

In [15]:
b = a[:2, 1:3]
b

array([[0, 0],
       [2, 3]])

In [16]:
a[1, :]

array([-1,  2,  3,  1])

In [17]:
a[1:2, :]

array([[-1,  2,  3,  1]])

In [18]:
a[[1], :]

array([[-1,  2,  3,  1]])

Индексы можно передавать в виде массива

In [19]:
b = np.array([0, 2, 1]) #индекс по столбцам
a[np.arange(3), b]

array([1, 3, 0])

Фильтрация значений происходит следующим образом - сначала создается маска из значений True/False, затем эта маска передается как индексы

In [20]:
a = np.array([[1,4], [3, 49], [-5, 6]])

idx = (a > 3)

idx

array([[False,  True],
       [False,  True],
       [False,  True]])

In [21]:
a[idx]

array([ 4, 49,  6])

In [22]:
a[a > 4]

array([49,  6])

### Операции с векторами

Можно использовать встроенные функции numpy для математических операций - например np.add для сложения векторов. Напомним, что данные операции производятся поэлементно

In [23]:
x = np.array([[1,1],[6,4]], dtype=np.float64)#можно дополнительно указать тип данных при создании массива
y = np.array([[5,2],[1,8]], dtype=np.float64)

print(x + y)
print(np.add(x, y))

[[ 6.  3.]
 [ 7. 12.]]
[[ 6.  3.]
 [ 7. 12.]]


Либо можно использовать операторы сложения/умножения

In [24]:
x - y

array([[-4., -1.],
       [ 5., -4.]])

In [25]:
np.subtract(x, y)

array([[-4., -1.],
       [ 5., -4.]])

In [26]:
x * y

array([[ 5.,  2.],
       [ 6., 32.]])

In [27]:
x / y

array([[0.2, 0.5],
       [6. , 0.5]])

In [28]:
np.divide(x, y)

array([[0.2, 0.5],
       [6. , 0.5]])

In [29]:
np.multiply(x, y)

array([[ 5.,  2.],
       [ 6., 32.]])

### Перемножение матриц

Для перемножения векторов и матриц используется метод dot

In [30]:
v = np.array([19,1])
w = np.array([11, 22])

print(v.dot(w))
print(np.dot(v, w))

231
231


In [31]:
print(x.dot(v))

[ 20. 118.]


In [32]:
x.dot(y)

array([[ 6., 10.],
       [34., 44.]])

In [33]:
x.T

array([[1., 6.],
       [1., 4.]])